# Generated by Django 6.1.1 on 2026-10-01 12:14

import django.db.models.deletion
import issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
            ],
            bases=(issues.models.BaseEntity, models.Model),
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=255)),
            ],
            bases=(issues.models.BaseEntity, models.Model),
        ),
        migrations.CreateModel(
            name='CriticalIssue',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.issue')),
            ],
            bases=('issues.issue',),
        ),
        migrations.CreateModel(
            name='LowPriorityIssue',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.issue')),
            ],
            bases=('issues.issue',),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.reporter'),
        ),
    ]
